# Generated by Django 5.0 on 2025-04-25 13:02

import datetime
import django.db.models.deletion
import loyer.models
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('nbre_bureau', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='imeuble/')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contract', models.FileField(upload_to='contrat/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.CharField(choices=[('1ere niveau', '1ere niveau'), ('2eme niveau', '2eme niveau'), ('3eme niveau', '3eme niveau'), ('4eme niveau', '4eme niveau')], max_length=20)),
                ('picture', models.ImageField(upload_to='bureau/')),
                ('num', models.PositiveIntegerField(default=1, unique=True)),
                ('picture1', models.ImageField(upload_to='bureau/')),
                ('picture2', models.ImageField(upload_to='bureau/')),
                ('Houseownerjoinedthesite', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rent_amount', models.PositiveIntegerField(default=0)),
                ('bordereau', models.ImageField(upload_to='bordeau/')),
                ('is_available', models.BooleanField(default=True)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyer.immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent_date', models.DateTimeField(blank=True, default=loyer.models.thirtyDays, verbose_name='Agreement started')),
                ('deposit_by_renter', models.PositiveIntegerField(default=0)),
                ('pay_inadvance', models.BooleanField(default=False)),
                ('amount_inadvance', models.PositiveIntegerField()),
                ('Paid_for_mounths', multiselectfield.db.fields.MultiSelectField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=47)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyer.locataire')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loyer.office')),
            ],
            options={
                'ordering': ('-office',),
            },
        ),
    ]
