# Generated by Django 5.0 on 2025-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeuble',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
