# Generated by Django 5.0 on 2025-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyer', '0002_immeuble_owner_name_immeuble_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeuble',
            name='nbre_chambres',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Rooms'),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='nbre_toilettes',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Toilets'),
        ),
    ]
